### ISSUE TITLE
Not compatible with liteloader?

### ISSUE THREAD

**Issue by elhertz** [biscuut/SkyblockAddons#1]
Log
https://pastebin.com/xsnsCUFA

**Comment by biscuut** [comment]
No sorry, it's not compatible with liteloader yet :(

**Comment by biscuut** [comment]
I made a temporary version that's compatible with liteloader, will work on tackling compatibility issues altogether when I get time: https://github.com/biscuut/SkyblockAddons/releases/download/v1.0-b6/SkyblockAddons-1.0-b6-LITELOADER.jar
