### ISSUE TITLE
Skeleton Bone Indicator

### ISSUE THREAD

**Issue by MCGamer00000** [biscuut/SkyblockAddons#100]
After the new update, the bones aren't being indicated properly and the "Hide bones" feature isn't working.
This is most likely due to how they fixed the bones becoming an Aiming target, so something about it must have changed.
![2019-09-11_20 50 33](https://user-images.githubusercontent.com/24983191/64745432-d947e180-d4d5-11e9-9dea-da1611620996.png)
In this picture I have the "Hide bones" feature enabled, and the indicator is supposed to be above my hotbar. As you can see, you can see the bones and there isn't any indicator.
As a programmer, I'd recommend looking at https://github.com/biscuut/SkyblockAddons/blob/master/src/main/java/codes/biscuit/skyblockaddons/mixins/MixinRenderManager.java#L27-L28
Possibly it's no longer riding a zombie or something? Looking at entity counts, it appears that it is indeed still riding something, but since it's invisible, I don't know exactly. what it is, or if it's changed.

**Comment by biscuut** [comment]
yeah i saw this issue, my guess is yeah doesnt ride a zombie

**Comment by biscuut** [comment]
Yep got it, fixed for next update
