### ISSUE TITLE
Summoning Eye alert can be replaced by ClientChatReceivedEvent

### ISSUE THREAD

**Issue by tomocrafter** [biscuut/SkyblockAddons#104]
Recently they fixed an issue where the message was not sent when a mob dropped a rare item. Therefore, it is now possible to more reliably determine whether or not you have obtained Summoning Eye with ClientChatReceivedEvent.

https://github.com/biscuut/SkyblockAddons/blob/3a4b2876e31ed62544015f26bb65e92805e379eb/src/main/java/codes/biscuit/skyblockaddons/utils/InventoryUtils.java#L132

**Comment by ViralTaco** [comment]
I agree, it can. I'm not sure it's worth it. The `getInventoryDifference()` method already runs in the background all the time and it's already comparing Strings. 
Adding code that basically does the same somewhere else wouldn't make much sense in my opinion. It's an inventory event. It is going to get caught by that method, having another one would be wasteful in my opinion. 

If you're forking the repo and you don't have the inventory feature then, yeah it's probably the best way to do it. 

I suggest Won't fix.

**Comment by tomocrafter** [comment]
It triggers when you get the summoning eye from ender chest or trade, so sometimes happen even if not get from zealot.

**Comment by biscuut** [comment]
tbh i'd really like to replace it but i dont have a good sword so cant get the exact color codes lol

**Comment by tomocrafter** [comment]
> tbh i'd really like to replace it but i dont have a good sword so cant get the exact color codes lol

Okay lol I am going to implement this one and create pull request when I get Summoning Eye, I hope it will drop as soon as possible to debug xD
