### ISSUE TITLE
Menu items are not translated when in a submenu for a menu item

### ISSUE THREAD

**Issue by joerkig** [biscuut/SkyblockAddons#106]
After clicking on the cogwheel to enter the settings of a menu item, the main menu items will not be translated.
![image](http://i.joerkig.com/kqqhqn.png)

**Comment by tomocrafter** [comment]
![image](https://user-images.githubusercontent.com/10905364/64939982-b898d680-d89d-11e9-8076-db8250b73f64.png)
![image](https://user-images.githubusercontent.com/10905364/64939990-bdf62100-d89d-11e9-8ef4-19b2d4447b3c.png)

Same problem here, I tried to open the issue on github but you already opened.

**Comment by biscuut** [comment]
got it thanks
