### ISSUE TITLE
All of item in skyblock has Unbreakable tag now

### ISSUE THREAD

**Issue by tomocrafter** [biscuut/SkyblockAddons#112]
So We can remove the "Hide the Tool Durability" Feature.

> ![image](https://user-images.githubusercontent.com/10905364/64946466-e9810780-d8ad-11e9-8792-f11d6d0955da.png)
> 🔗 https://hypixel.net/threads/skyblock-patch-0-7-1.2280493/

**Comment by biscuut** [comment]
Oh I didnt even know 1.8 had the unbreakable tag, I wonder why they didnt do that in the first place haha
