### ISSUE TITLE
Items in chests missing background when selected

### ISSUE THREAD

**Issue by TCreopargh** [biscuut/SkyblockAddons#113]
![7c471e29d47bddfd](https://user-images.githubusercontent.com/16634689/64947721-306bfe80-d8a8-11e9-80e9-db765384743f.jpg)
![-3bb0c89143870471](https://user-images.githubusercontent.com/16634689/64947724-31049500-d8a8-11e9-83d8-de1b7cf95aa5.jpg)
Items in chests should normally have a white background when selected, but it's missing.
When switched to the old version of sba, the glitch is resolved. So it's a bug with the new version of sba.

**Comment by biscuut** [comment]
Fixed this for next patch thanks
