### ISSUE TITLE
BUG Avoid breaking bottom sugarcane implementation is wrong.

### ISSUE THREAD

**Issue by ViralTaco** [biscuut/SkyblockAddons#114]
Look here: [MixinPlayerControllerMP.java Line 52](https://github.com/biscuut/SkyblockAddons/blob/a19092f570fb2ce17b483f1fcfe6dd82ab72ae2b/src/main/java/codes/biscuit/skyblockaddons/mixins/MixinPlayerControllerMP.java#L52)
It's just plain wrong. Here is the working version: [MixinPlayerControllerMP.java Line 39](https://github.com/fsckmc/SkyblockAddons/blob/027d8221bb6df6a8a6e2aaf4b7b08d94d4c32f7e/src/main/java/codes/biscuit/skyblockaddons/mixins/MixinPlayerControllerMP.java#L39) Commit: 027d8221bb6df6a8a6e2aaf4b7b08d94d4c32f7e

Your implementation doesn't work with a stone hoe such as the rookie hoe. 
Either that or the message is wrong. ie: you can't break the bottom block with bare hands. Since you check `if (heldItem == null || /*hoes, sugarcane*/)`
@biscuut 
Thank you for your time

**Comment by biscuut** [comment]
Message was wrong thanks
