### ISSUE TITLE
make items you don't want to not be picked up

### ISSUE THREAD

**Issue by DarkRedeemer77** [biscuut/SkyblockAddons#124]
Can you make a setting where you can type in items that you don't want to pick up which could be helpful while grinding

**Comment by ViralTaco** [comment]
Afaik that is handled on the server side. 
Some hacked client have a feature that automatically drops low value items. That is considered an unfair advantage.

**Comment by biscuut** [comment]
Yeah I agree pretty sure its server side on  hypixel, and even if it isn't I don't really consider that legit

**Comment by tomocrafter** [comment]
I can make this feature, but It violates the Hypixel rule.

**Comment by DarkRedeemer77** [comment]
sry i didnt know
