### ISSUE TITLE
Locked Slot incompatible with Mouse Tweak

### ISSUE THREAD

**Issue by SteveKunG** [biscuut/SkyblockAddons#137]
As title said, When locked some item and shift+click+drag. Items comes out from locked slot.

![2019-09-28_14 45 50](https://user-images.githubusercontent.com/6128413/65813371-b3714b00-e1fe-11e9-8f9b-42524d6daa94.png)
![2019-09-28_14 45 55](https://user-images.githubusercontent.com/6128413/65813372-b3714b00-e1fe-11e9-823a-55e3348d8b98.png)

**Comment by biscuut** [comment]
Yeah i've seen this, not really sure if theres much I can do though, will have to check it out

**Comment by biscuut** [comment]
should be fixed in #142
