### ISSUE TITLE
Option to disable Night Vision

### ISSUE THREAD

**Issue by MCGamer00000** [biscuut/SkyblockAddons#138]
(Please mark as Enhancement, this isn't an issue)
So I was looking on the forums and saw how there was Night Vision charm. However, people complained that it was glitched whenever there they are on an island with a day saver. (I myself don't have the talisman, so idk if its true, but I could see it being possible)

So I figured, hey, maybe you could add an option to simply make the Night Vision either not blink, or do nothing. If it were to not blink, they could be considered a minor unfair advantage, but if it were to be disabled, it wouldn't shouldn't be considered an advantage.
Of course, have it default set to disabled, just so people don't complain about it disabling night vision out of the box.

I have only seen an different person's opinion about the effect, so I don't know if its true, so I'd recommend to do a bit of research and find out what happens and figure out how to help without giving an unfair advantage.

**Comment by DidiSkywalker** [comment]
I think #134 already solves this?

**Comment by MCGamer00000** [comment]
> I think #134 already solves this?

Yeah, you're right. Didn't think to look in pull requests. Thanks.
Closing.
