### ISSUE TITLE
Wrong mappings version

### ISSUE THREAD

**Issue by mdashlw** [biscuut/SkyblockAddons#2]
The current mappings are `stable_20` which were made for 1.8.8,
for 1.8.9 use `stable_22`

https://github.com/biscuut/SkyblockAddons/blob/9e7eefdde20751ff7fd008a403ca851d593d27ae/build.gradle#L44

**Comment by biscuut** [comment]
ah didn't even realize, luckily there aren't too many changes. fixed.
