### ISSUE TITLE
Bug with Absorption and the health bar

### ISSUE THREAD

**Issue by Javahase** [biscuut/SkyblockAddons#20]
I have discovered that after I get the absorption effect, the healthbar will show a value which really seems to be false since absorption shouldn't give me that much hearts. I verified it by looking on my health without the mod.
Mod with absorption:
![image](https://user-images.githubusercontent.com/42071641/62277122-c3aabb00-b445-11e9-8a26-b7ed3668a274.png)
Vanilla with absorption:
![image](https://user-images.githubusercontent.com/42071641/62277192-ef2da580-b445-11e9-84e2-20af62a871c2.png)

**Comment by biscuut** [comment]
ok thanks, i will check it out

**Comment by biscuut** [comment]
Okay, the problem was because the orange color is &6, and it thought 6 was part of the health. Will be fixed in next patch :)
