### ISSUE TITLE
Adding chinese localization

### ISSUE THREAD

**Issue by misterplus** [biscuut/SkyblockAddons#3]
There's a lot of chinese players enjoying skyblock, I can see them loving this mod, by any chance if this mod has a lang file? I can provide a localized file for simplified chinese.

**Comment by biscuut** [comment]
Hi there, I have added a lang file here: https://github.com/biscuut/SkyblockAddons/blob/master/src/main/resources/lang/en_US.json . Feel free to translate it and then make a pull request or just send it etc.
