### ISSUE TITLE
Enchantement UI split word

### ISSUE THREAD

**Issue by SRThibaultP** [biscuut/SkyblockAddons#33]
I finded a another word for french but I post here in case of other problem for a another language file.
![image](https://user-images.githubusercontent.com/42326001/62525043-fb937300-b836-11e9-9d23-d86a6cabf0c8.png)
(Showing the sentence "Enchantements à correspond" instead of "Enchantements à correspondre". So the sentence is splitted after 27 characters.)

**Comment by biscuut** [comment]
Okay thanks! I will probably move it a more to the left to make space for other languages.
