### ISSUE TITLE
Backpack preview causes sky to change color/brightness

### ISSUE THREAD

**Issue by Kiriot22** [biscuut/SkyblockAddons#50]
Gif:
![nyCPpBk1fU](https://user-images.githubusercontent.com/9750071/63470832-eab94300-c46d-11e9-8360-c9101f25ee9f.gif)

**Comment by biscuut** [comment]
Will check this out thank you.

**Comment by biscuut** [comment]
ay okay I think I fixed this now 😄 . I'm super bad at Minecraft lighting so my bad xd
