### ISSUE TITLE
Item pickup log shows whole inventory when exiting merchant

### ISSUE THREAD

**Issue by ViralTaco** [biscuut/SkyblockAddons#54]
Hi, 
I caught this: ![](https://i.ibb.co/vh2k0sj/2019-08-22-23-59-10.png)
I'm not sure how it happens but it seems pretty consistent. 

Steps to reproduce: 
1. In the village click on a merchant
2. exit the menu

And looking at it again I think I might have an explanation for it… 
The name of all the items in the player's inventory is changed to include the number of each items inlined with the name. "Lore" is also added on some items for the price.
ie: a single potato becomes "potato x1"

Given that it's just a quirk with how skyblock's merchant system works I propose marking this as "won't fix", it's a harmless "bug" and I'm not sure it's worth the added code complexity.

**Comment by biscuut** [comment]
ok i made a workaround, thank you very much
