### ISSUE TITLE
[Feature request] Hotbar lock

### ISSUE THREAD

**Issue by TCreopargh** [biscuut/SkyblockAddons#79]
It would be really nice if we can lock some certain slots in the Hotbar so that we can never accidentally sell/drop our precious items by mistake. 
I accidentally threw my runaans bow when sorting out my inventory and some random guy picked it up and refused to give back. Now I have a 50mil Midas and I'm very afraid to lose it. Adding this feature will help a lot. Thanks!

**Comment by biscuut** [comment]
Yeye will be adding slot locker in next update

**Comment by fsckmc** [comment]
I wrote a way to disable inventory drag + dropping of ItemStack's that have a lore containing a rarity of a certain amount, the UI framework you use doesn't seem to support dropdowns, so currently it's a very hacky /sba setrarity {1,2,3,4,5} etc.

Happy to push it to my fork and submit a PR, unless you'd rather implement it yourself, I'm slightly concerned about WatchDog detecting it though, I'm not sending any custom packets but it's not clear atm if the InventoryDragEvent is client side, so cancelling it won't cause WatchDog to see an anomaly.  I joined the discord, would love to chat more about this.

**Comment by ViralTaco** [comment]
@fsckmc 
To be honest I'm not a fan of the idea, especially since it involves checking strings all the time. There is already too much of that imho. I play on a laptop. :/ 
but eh if you have the code you can always make a pull request and just reference the id here

**Comment by fsckmc** [comment]
It only checks strings on a drop event, which happens rarely. I've profiled it and it's not that bad, I haven't added the drop event to the branch yet, due to ItemTossEvent not cancelling properly, I may need to write a custom mixin Injection to handle that.

https://github.com/fsckmc/SkyblockAddons/tree/feature-rarity-detection-antidrop

You can see how I'm checking, also added a small utility "library" to check rarity of items.

Could you elaborate what you mean by "involves checking strings all the time" perhaps I'm missing something.

**Comment by ViralTaco** [comment]
> Could you elaborate what you mean by "involves checking strings all the time"

Sure thing. here is a String `"I am a string."` here is a method 
```
@override public Boolean equals(String theString) {
    if (theString == null) 
        return false;
    if (theString == this)
        return true;
    if (theString.length != this.length)
        return false;

    char[] theStringAsArray = theString.toCharArray();
    char[] thisAsArray = this.toCharArray();
    for (int i = 0; i < this.length; ++i) {
        if (thisAsArray[i] != theStringAsArray[i])
            return false;
    }
    return true;
}
```

That method is linear O(n). You no doubt understand the implications. 
Here is another example of a linear algorithm: [sleep sort](https://rosettacode.org/wiki/Sorting_algorithms/Sleep_sort#Java)

_All that being said, the fact that you used the drop event makes this whole passive-aggressive rambling unnecessary…_ I did work hard on it though, so I put this disclaimer at the end.

**Comment by fsckmc** [comment]
Really not entirely sure what to say other than I guess this may have provided some useful links to people who are interested in algorithms?
