### ISSUE TITLE
The mod cannot detect the game when using hypixel translation

### ISSUE THREAD

**Issue by Dayuan-mc** [biscuut/SkyblockAddons#90]
[https://github.com/biscuut/SkyblockAddons/blob/master/src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java#L92](https://github.com/biscuut/SkyblockAddons/blob/master/src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java#L92)
`startsWith("SKYBLOCK")`

but
![image](https://user-images.githubusercontent.com/8676167/64059346-24681780-cbed-11e9-9b92-08ea7817d1f8.png)(Chinese translation)

i think there should be a option to choose what to detect.

**Comment by biscuut** [comment]
Yeah i'm aware of this issue but i can't reproduce it. I changed my language but the scoareboard doesn't change? How are you changing your language?

**Comment by Dayuan-mc** [comment]
> Yeah i'm aware of this issue but i can't reproduce it. I changed my language but the scoareboard doesn't change? How are you changing your language?

/language CHINESE_SIMPLIFIED

**Comment by Dayuan-mc** [comment]
For now, only simplified Chinese changes the scoreboard title.

**Comment by Dayuan-mc** [comment]
#91

**Comment by biscuut** [comment]
> 
> 
> > Yeah i'm aware of this issue but i can't reproduce it. I changed my language but the scoareboard doesn't change? How are you changing your language?
> 
> /language CHINESE_SIMPLIFIED

Yeah thats the thing, i changed the language but the scoreboard doesnt change, i will have to mess around more because i want to make sure i support all the languages

**Comment by biscuut** [comment]
ah its because i was in a coop, alright now i'll test it
